# services:
#   postgres:
#     image: bitnami/postgresql:latest
#     ports:
#       - 5432:5432
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: docker
#       POSTGRES_USER: docker
#       POSTGRES_DB: depara-conversion-v1
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

services:
#===============================================================================
# POSTGRES DATABASE
#===============================================================================
  postgres:
      image: bitnami/postgresql:latest
      container_name: deparav2-postgresql
      ports:
      - 5432:5432
      restart: always
      environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: depara-v2
